### ISSUE TITLE
How to interpret result of test_fitb.py?

### ISSUE THREAD

**Issue by davidsonic** [gcucurull/visual-compatibility#1]
Hi, 
Thanks for releasing the code! I got the following result.
![image](https://user-images.githubusercontent.com/15846113/59967604-448aa480-94e1-11e9-9238-d23436b5b0b5.png)
When I set k=15, I got exactly the same result. How do I interpret these two results as opposed to the one shown in the paper?
![image](https://user-images.githubusercontent.com/15846113/59967618-73087f80-94e1-11e9-8c3b-0d20de5193ca.png)
where one is 62.6 and another is 96.9?

**Comment by Charlie1994** [comment]
The result you highlighted is the accuracy of edge prediction rather than the FITB prediction result. See line 134, that print function outputs the FITB accuracy results.
