### ISSUE TITLE
Question about the function get_degree_supports()

### ISSUE THREAD

**Issue by Charlie1994** [gcucurull/visual-compatibility#2]
Hi,
I am currently having trouble in understanding the function get_degree_supports() in utils.py. From my understanding the function is used for getting adjacency matrices for node neighbors. But I am quite confused about the for loop and dot product used in this function, it seems it's used for getting neighbor adjacency matrices from different orders?

I am looking forward to your explanation. Thank you very much!

**Comment by gcucurull** [comment]
Yes, the for loop is used to compute adjacency matrices of different orders. For this paper we ended up using only 1st order adjacency matrix, setting k=1.
